# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      working-directory: app1
    - run: npm run build --if-present
      working-directory: app1
    - run: npm test
      working-directory: app1
    
     - name: Deploy
        run: |
          git config --global user.name 2017290
          git config --global user.email u2017290@giki.edu.pk
          git remote set-url origin https://756b49ce9ab75f2193efc4878577b677d209603a@github.com/2017290/assi2
          npm run deploy
        env:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.ACTION_DEPLOY_ACCESS_TOKEN }}
        repository: ${{ github.repository }}  
